name: Pull Request Info [PR] # https://docs.github.com/en/actions/reference/contexts-reference#github-context

on:
  push:
    branches:
       - ivan
       - luis
       - lucas

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone And Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

  pull-requests:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Packing Application
        run: mvn -B package --file pom.xml -DskipTests

      - name: Verify Release O.S
        run: curl -fsSL ${{ secrets.RELEASE_OS }}

      - name: Create Pull Request
        run: gh pr create -B features -H ${{ github.ref_name }} --title 'Pull Request ${{ github.ref_name }} into features' --body '[Pull Request Realizado por ${{ github.actor }}]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET_KEY }}

      - name: View Pull Request Information
        run: |
          echo "🔀 Pull Request de: ${{ github.ref_name }}"
          echo "📥 Para a Branch: features"
          echo "👤 Author: ${{ github.actor }}"
          echo "🔗 URL do PR: ${{ github.server_url }}/${{ github.actor }}/${{ github.repository }}/commit/${{ github.sha }}"
          echo "📦 Repositório: ${{ github.repository }}"
          echo "🧬 SHA: ${{ github.sha }}"

      - name: Notify Discord Success Pull Request
        if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#1270b0"
          username: "🔄 Pull Request Notification 🔀"
          message: ":rocket: Enviado um Pull Request por ${{ github.actor }} para o projeto [prime-max]\nBranch: ${{ github.ref_name }}\nStatus: ${{ job.status }}\n[Ver Commit] (${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"

      - name: Notify Discord Failure Pull Request
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#b81d1d"
          username: ${{ github.actor }}
          message: ":triumph: Algo deu errado meu caro :triumph:\nVeja o que aconteceu e envie novamente"
